name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-test-lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -e .[app,dev]

            - name: Check code formatting with Ruff
              run: ruff format --check .

            - name: Lint with Ruff
              run: ruff check .

            - name: Type check with mypy
              run: mypy grid_universe

            - name: Run tests
              run: pytest --cov=grid_universe --cov-report=term-missing
